export const routes = {
  test: "/test",
  home: "/",
  login: "/login",
  register: "/register",
  apartmentRent: "/cho-thue-can-ho",
  groundRent: "/cho-thue-mat-bang",
  motelRoomRent: "/cho-thue-phong-tro",
  houseRent: "/nha-cho-thue",
  search: "/search/:params",
  profile: "/profile",
  editProfile: "/edit-profile",
  createPost: "/create-post",
  postDetail: "/post-detail/:id",
  personalUser: "/user/:id",
  managePost: "/manage-post",
};
