export const routes = {
  test: "/test",
  home: "/",
  login: "/login",
  register: "/register",
  search: "/search/:params",
  profile: "/profile",
  editProfile: "/edit-profile",
  createPost: "/create-post",
  postDetail: "/post-detail/:id",
  personalUser: "/user/:id",
  managePost: "/manage-post",
  savePost: "/save-post",
  follow: "/follow",
  dashboard: "/dashboard",
  manageCategory: "/dashboard/manage-category",
  manageUser: "/dashboard/manage-user",
  managePosts: "/dashboard/manage-post",
  chat: "/chat",
};
